import React, { useState } from 'react';
import { AnomalyCallout } from './AnomalyCallout';
import { CopilotPanel } from './CopilotPanel';
import type { AIAssistantProps, CopilotMessage } from './types';

// ─── Phase 1 mock data ────────────────────────────────────────────────────────
// Hardcoded so every UI state is visually testable without API calls.
// Phase 2: replace with values derived from Pulse contextData.
// Phase 3: anomaly generated by the model; messages populated from stream.

const MOCK_ANOMALY = {
  headline:    'B2B bookings down 18% month-over-month',
  explanation: '3 enterprise accounts paused activity in October. Chicago and Atlanta markets account for 71% of the shortfall.',
  dataSource:  'Based on MonthlyRevenue, Oct 2024',
  severity:    'warning' as const,
};

const MOCK_MESSAGES: CopilotMessage[] = [
  {
    role:    'user',
    content: 'Why did B2B revenue drop in October?',
  },
  {
    role:     'assistant',
    content:  'B2B revenue declined 18% in October, driven primarily by 3 enterprise accounts that paused activity: Allstate (Chicago), Deloitte (Atlanta), and Accenture (New York). These three accounts represented $84K of the prior month\'s recurring spend.\n\nHistorically, accounts that pause in Q4 resume activity in January–February. No accounts have formally churned.',
    citation: 'Based on MonthlyRevenue data',
  },
  {
    role:    'user',
    content: 'Which market should I prioritize to recover the shortfall?',
  },
  {
    role:     'assistant',
    content:  'Based on venue density and active pipeline, Atlanta has the strongest recovery potential. 4 venues currently have available inventory matching the paused account profiles, and Atlanta averaged 23% quarter-over-quarter growth across 2024.',
    citation: 'Based on MonthlyRevenue + EnterpriseEngagementSummary data',
  },
];

// ─── Component ────────────────────────────────────────────────────────────────

/**
 * Context-aware wrapper shell for the AI copilot layer.
 *
 * Phase 1: manages UI state (anomaly visible, panel expanded) and renders
 *          hard-coded mock data so every visual state is testable.
 * Phase 2: receives real Pulse contextData; mock data replaced with computed
 *          anomaly detection and summary stats.
 * Phase 3: onSubmit fires Anthropic API; messages populated from stream
 *          with citation enforcement.
 *
 * Usage:
 *   <AIAssistant context="dashboard">
 *     {children}   ← existing dashboard content, untouched
 *   </AIAssistant>
 *
 * Renders as a React Fragment so it participates in the parent's flex layout
 * without adding a wrapping DOM node.
 */
export function AIAssistant({
  context,      // eslint-disable-line @typescript-eslint/no-unused-vars  — used in Phase 2+
  contextData,  // eslint-disable-line @typescript-eslint/no-unused-vars  — used in Phase 2+
  children,
}: AIAssistantProps) {
  // AnomalyCallout starts visible so the design can be reviewed on first load.
  // In production (Phase 3) this will default to false and flip true when the
  // model detects an anomaly worth surfacing.
  const [showAnomaly, setShowAnomaly]   = useState(true);
  const [panelExpanded, setPanelExpanded] = useState(false);

  // Phase 1: messages are static. Phase 3: append on each API response chunk.
  const [messages] = useState<CopilotMessage[]>(MOCK_MESSAGES);

  /** Phase 3 replacement: push user message, call Anthropic, stream response. */
  const handleSubmit = (_query: string) => {
    // no-op in Phase 1
  };

  return (
    <>
      {showAnomaly && (
        <AnomalyCallout
          {...MOCK_ANOMALY}
          onDismiss={() => setShowAnomaly(false)}
        />
      )}

      {children}

      <CopilotPanel
        isExpanded={panelExpanded}
        onToggle={() => setPanelExpanded((p) => !p)}
        messages={messages}
        onSubmit={handleSubmit}
      />
    </>
  );
}
